todolist_homepage:
    path:     /
    defaults: { _controller: ToDoListBundle:TasksList:index }

todolist_taskslist_list:
    path:     /taskslist
    defaults: { _controller: ToDoListBundle:TasksList:getTasksList }
