todolist_homepage:
    path:     /
    defaults: { _controller: ToDoListBundle:TasksList:index }

todolist_taskslist:
    path:     /taskslist
    defaults: { _controller: ToDoListBundle:TasksList:getTasksList }

todolist_new_tasklist:
    pattern:  /taskslist/new
    defaults: { _controller: ToDoListBundle:TasksList:newTaskList }

todolist_update_tasklist:
    pattern: /taskslist/update/{idList}
    defaults: { _controller: ToDoListBundle:TasksList:updateTaskList }
    requirements:
        idList: \d+

todolist_delete_tasklist:
    pattern: /taskslist/delete/{idList}
    defaults: { _controller: ToDoListBundle:TasksList:deleteTaskList }
    requirements:
        idList: \d+

todolist_tasks:
    pattern:  /taskslist/{idList}
    defaults: { _controller: ToDoListBundle:Task:getTasks }
    requirements:
        idList: \d+
