todolist_homepage:
    path:     /
    defaults: { _controller: ToDoListBundle:TasksList:index }

todolist_taskslist:
    path:     /taskslist
    defaults: { _controller: ToDoListBundle:TasksList:getTasksList }

todolist_add_tasklist:
    pattern:  /taskslist/add
    defaults: { _controller: ToDoListBundle:TasksList:addTaskList }

todolist_update_tasklist:
    pattern: /taskslist/update/{idList}
    defaults: { _controller: ToDoListBundle:TasksList:updateTaskList }
    requirements:
        idList: \d+

todolist_delete_tasklist:
    pattern: /taskslist/delete/{idList}
    defaults: { _controller: ToDoListBundle:TasksList:deleteTaskList }
    requirements:
        idList: \d+

todolist_tasks:
    pattern:  /taskslist/{idList}/tasks
    defaults: { _controller: ToDoListBundle:Task:getTasks }
    requirements:
        idList: \d+

todolist_add_tasks:
    pattern:  /taskslist/{idList}/tasks/add
    defaults: { _controller: ToDoListBundle:Task:addTask }
    requirements:
        idTaskList: \d+
